AWS_ACCESS_KEY = "" 
AWS_SECRET_KEY = "" 

REGION = "us-west-2" 
AVAILABILITY_ZONE = "us-west-2a"
AMI_ID = "ami-017bf00eb0d4c7182"
INSTANCE_TYPE  = "t2.micro"

VM_NAME = "VM01" 
INSTANCE_USERNAME = "" 
INSTANCE_PASSWORD = "" 



